{
    anytime: [
				"Hey there sexy!",
				"You're a smart cookie.",
				"You have impeccable manners.",
				"I appreciate you.",
				"You are enough.",
				"You're strong.",
				"Your perspective is refreshing.",
				"I'm grateful to know you.",
				"You light up the room.",
				"You deserve a hug right now.",
				"You should be proud of yourself.",
				"You're more helpful than you realize.",
				"You're all that and a super-size bag of chips.",
				"On a scale from 1 to 10, you're an 11.",
				"You are strong.",
				"You're even more beautiful on the inside than you are on the outside.",
				"I'm inspired by you.",
				"You're like a ray of sunshine on a really dreary day.",
				"You are making a difference.",
				"Thank you for being there for me.",
				"You bring out the best in other people.",
				"You're a great listener.",
				"How is it that you always look great, even in sweatpants?",
				"Everything would be better if more people were like you!",
				"I bet you sweat glitter.",
				"That color is perfect on you.",
				"Being around you makes everything better!",
				"When you say, "I meant to do that," I totally believe you.",
				"When you're not afraid to be yourself is when you're most incredible.",
				"Colors seem brighter when you're around.",
				"That thing you don't like about yourself is what makes you so interesting.",
				"You're wonderful.",
				"You have cute elbows. ",
				"You're better than a triple-scoop ice cream cone. With sprinkles.",
				"When I'm down you always say something encouraging to help me feel better.",
				"You are really kind to people around you.",
				"You're one of a kind!",
				"You should be thanked more often. So thank you!",
				"You have the best ideas.",
				"You always find something special in the most ordinary things.",
				"Everyone gets knocked down sometimes, but you always get back up and keep going.",
				"You're a candle in the darkness.",
				"You're a great example to others.",
				"Being around you is like being on a happy little vacation.",
				"You always know just what to say.",
				"You're always learning new things and trying to better yourself, which is awesome.",
				"If someone based an Internet meme on you, it would have impeccable grammar.",
				"You could survive a Zombie apocalypse.",
				"You're more fun than bubble wrap.",
				"When you make a mistake, you try to fix it.",
				"Who raised you? They deserve a medal for a job well done.",
				"You're great at figuring stuff out.",
				"Your voice is magnificent.",
				"The people you love are lucky to have you in their lives.",
				"You're like a breath of fresh air.",
				"You make my insides jump around in the best way.",
				"You're so thoughtful.",
				"Your creative potential seems limitless.",
				"Your quirks are so you -- and I love that.",
				"When you say you will do something, I trust you.",
				"Somehow you make time stop and fly at the same time.",
				"When you make up your mind about something, nothing stands in your way.",
				"You seem to really know who you are.",
				"Any team would be lucky to have you on it.",
				"You bring out the best in people and show people how to live with courage.",
				"I admire your patience and ability to remain calm during times of distress.",
				"I appreciate how much you show you care about other people.",
				"You have a heart of gold that benefits so many people in your life.",
				"You can accomplish anything that you put your mind to.",
				"I admire you.",
				"You are so worth loving. ",
				"You're more amazing than you will ever realize.",
				"You are one of a kind and it continues to impress me.",
				"You're not wearing any makeup? Wow, you are flawless.",
				"You make that outfit look amazing, not many people could pull that off like you do!",
				"I always get lost in your eyes.",
				"You are radiant.",
				"There’s a beautiful softness behind your eyes.",
				"You are glowing.",
				"You always make ordinary things look great.",
				"Your smile is infectious.",
				"Your intelligence and curiosity inspire me.",
				"I always learn so many interesting and thought-provoking things from you.",
				"You seem to really know who you are.",
				"I don't care if its rude to stare, you're cute, therefore I shall stare . ",
				"I truly respect and value your thoughts and ideas.",
				"I could not have come up with the answer without you.",
				"I feel like you know something about everything.",
				"You always provide valuable insight into other people.",
				"Your smile is contagious.",
				"I bet you make babies smile.",
				"You have the best laugh.",
				"You light up the room.",
				"You have a great sense of humor.",
				"If cartoon bluebirds were real, a couple of 'em would be sitting on your shoulders singing right now.",
				"You're like sunshine on a rainy day.",
				"You bring out the best in other people.",
				"I bet you sweat glitter.",
				"Colors seem brighter when you're around.",
				"You're more fun than a ball pit filled with candy.",
				"Jokes are funnier when you tell them.",
				"You always know how to find that silver lining.",
				"You're a candle in the darkness.",
				"Being around you is like a happy little vacation.",
				"You're more fun than bubble wrap.",
				"You're like a breath of fresh air.",
				"You're someone's reason to smile.",
				"How do you keep being so funny and making everyone laugh?",
				"Is that your picture next to "charming" in the dictionary?",
				"Your kindness is a balm to all who encounter it.",
				"You are brave.",
				"Your insides are even more beautiful than your outside.",
				"You have the courage of your convictions.",
				"You're a great listener.",
				"You were cool way before hipsters were cool.",
				"That thing you don't like about yourself is what makes you really interesting.",
				"You're inspiring.",
				"You're so thoughtful.",
				"When you make up your mind, nothing stands in your way.",
				"You seem to really know who you are.",
				"You're a smart cookie.",
				"Your perspective is refreshing.",
				"Your ability to recall random factoids at just the right times is impressive.",
				"When you say, "I meant to do that," I totally believe you.",
				"You have the best ideas.",
				"You're always learning new things and trying to better yourself. That's awesome.",
				"If someone based an Internet meme on you, it would have impeccable grammar.",
				"You could survive a zombie apocalypse.",
				"When you make a mistake, you fix it.",
				"You're great at figuring stuff out.",
				"Your creative potential seems limitless.",
				"I bet you do crossword puzzles in ink.",
				"You have a good head on your shoulders.",
				"Everyone gets knocked down sometimes; only people like you get back up again and keep going.",
				"You should be proud of yourself.",
				"You are making a difference.",
				"You deserve a hug right now.",
				"You're a great example to others.",
				"Actions speak louder than words, and yours tell an incredible story.",
				"You're more helpful than you realize.",
				"Hanging out with you is always fun.",
				"That thing where you know when someone needs something? That's amazing.",
				"Being around you makes everything better.",
				"You should be thanked more often. Thank you.",
				"Our community is better because you're in it.",
				"Someone is getting through something hard right now because you've got their back. Nice work.",
				"You always know just what to say.",
				"The people you love are lucky to have you in their lives.",
				"You smell really good.",
				"You may dance like no one's watching, but everyone's watching because you're mesmerizing.",
				"You have cute elbows. For real.",
				"Your bellybutton is kind of adorable.",
				"Your voice is magnificent.",
				"Your name suits you to a T.",
				"You're irresistible when you blush.",
				"Has anyone ever told you that you have great posture?",
				"I appreciate you.",
				"You are the most perfect you there is.",
				"You are enough.",
				"You're all that and a super-size bag of chips.",
				"On a scale from 1 to 10, you're an 11.",
				"You've got all the right moves.",
				"Everything would be better if more people were like you.",
				"When you're not afraid to be yourself, that's when you're incredible.",
				"You're wonderful.",
				"You're better than a triple-scoop ice cream cone. With sprinkles.",
				"You're one of a kind.",
				"If you were a box of crayons, you'd be the big industrial name-brand one with a built-in sharpener.",
				"Who raised you? They deserve a medal for a job well done.",
				"Somehow you make time stop and fly all at the same time.",
				"There's ordinary, and then there's you.",
				"You're even better than a unicorn because you're real.",
				"You're really something special."
			], morning: [
				"Good morning, beautiful!",
				"Enjoy your day!",
				"How was your sleep?",
				"I like your style.",
				"Your hair looks stunning.",
				"Don't forget the coffee.",
				"I bet you do the crossword puzzle in ink.",
				"Thank you for being you.",
				"You always make my day better when I am feeling down.",
				"You make everyone feel so welcome, I don't think you have ever met a stranger.",
				"You are so easy to be around and you always have something interesting to talk about.",
				"Your confidence is refreshing, and there is no question as to why you are so self-assured.",
				"You look great today!",
        "What a great day today!",
        "You make the difference today!",
        "A beautiful smile, for a beautiful day",
        "Are you still looking at the mirror?",
        "How good your hair is today!",
        "Start the day with a smile!",
        "It will be a beautiful day again!",
        "Isn't it a nice day?",
        "Prepare for a fun day!"
			],			 
			afternoon: [
				"Hello, beauty!",
				"You look sexy!",
				"Looking good today!",
				"Any team would be lucky to have you on it.",
				"Defenseless animals are drawn to you.",
				"The way you treasure your loved ones is incredible.",
				"You're a gift to those around you.",
				"You're gorgeous — and that's the least interesting thing about you, too.",
				"You look great today.",
				"Your eyes are breathtaking.",
				"How is it that you always look so great, even if you're in ratty pajamas?",
				"That color is perfect on you.",
				"Just finish your work ...",
        "Noon, not evening, not morning",
        "Isn't this a nice day?",
        "Almost dinner time!"
			],
			evening: [
				"Wow, you look hot!",
				"You look nice!",
				"Hi, sexy!",
				"Babies and small animals probably love you.",
				"If you were a scented candle they'd call it Perfectly Imperfect (and it would smell like summer).",
				"There's ordinary, and then there's you.",
				"You're someone's reason to smile.",
				"You're even better than a unicorn, because you're real.",
				"How do you keep being so funny and making everyone laugh?",
				"You have a good head on your shoulders.",
				"The way you treasure your loved ones is incredible.",
				"You're really something special.",
				"Enjoy your meal!",
        "Just rest, wonderful ....",
        "You made the difference!",
        "Was the food good?"
			]
}
